# Generated by Django 3.1.5 on 2021-01-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aca_name', models.CharField(max_length=15)),
                ('aca_surname', models.CharField(max_length=15)),
                ('aca_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('c_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('c_academician', models.ManyToManyField(to='proje.Academician')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=15)),
                ('s_surname', models.CharField(max_length=15)),
                ('s_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proje.courses')),
            ],
        ),
        migrations.CreateModel(
            name='LectureNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proje.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proje.courses')),
            ],
        ),
    ]
